---
- hosts: all
  gather_facts: false

  vars_prompt:
    - name: username
      prompt: "Enter Windows username"
      private: false
    - name: password
      prompt: "Enter password for Windows user"

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
    ansible_winrm_server_cert_validation: 'ignore'
    ansible_winrm_transport: ntlm
    ansible_connection: 'winrm'

  tasks:
    - name: run win_ping
      win_ping:
