

name: deploy ansible

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
      runs-on: ubuntu-latest     
      steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: Lint Ansible Playbooks
        uses: ansible/ansible-lint-action@main
        with:
          targets: ""

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/ansible
      env: 
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}